# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Test Deploy

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x]
        steps:
            - name: Checkout the Repository
              uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: install dependencies
              run: npm install
            - name: run tests
              run: npm test
    deploy:
        runs-on: ubuntu-latest
        needs: build-test
        steps:
            - name: Deploy to Production
              uses: johnbeynon/render-deploy-action@v.0.0.8
              with:
                  service-id: ${{ secrets.SERVICE_ID }}
                  service-url: ${{ secrets.RENDER_TOKEN }}
